### ISSUE TITLE
请检查一下第10章节中数学公式显示是否有问题

### ISSUE THREAD

**Issue by RobertIndie** [Mouse0w0/lwjglbook-CN-Translation#2]
原书上的公式显示出现了问题，我不知道我们这个会不会也出问题。

![y o4i9s 45udn p n7n h](https://user-images.githubusercontent.com/16974619/41584997-57d7c446-73db-11e8-94df-f2f886cd2e07.png)

**Comment by mouse0w0** [comment]
由于所使用的Markdown解析器并不支持数学公式的解析，所以这个问题暂时不能解决
